approvedGitRepositories:
  - "**"

cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

enableScripts: false

globalFolder: .yarn/global

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

npmMinimalAgeGate: 0

packageExtensions:
  babel-plugin-inferno@*:
    peerDependencies:
      "@babel/core": "*"
  eslint-plugin-sonarjs@*:
    dependencies:
      ts-api-utils: ^2.4.0

pnpEnableEsmLoader: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.15.0.cjs
